version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xmlxsd_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    user: "www-data"
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        if [ ! -d vendor ]; then
          composer install --no-interaction --prefer-dist;
        fi &&
        if [ ! -f .env ]; then
          cp .env.example .env;
        fi &&
        php artisan key:generate &&
        sleep 5 &&
        php artisan migrate --force &&
        php-fpm
      "
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xmlxsd_queue
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      mysql:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      sh -c "
        sleep 15 &&
        php artisan queue:work --verbose --tries=3 --timeout=90
      "
    networks:
      - laravel

  frontend:
    image: node:20
    container_name: xmlxsd_frontend
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: >
      sh -c "
        npm install &&
        npm run build
      "
    depends_on:
      - app
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: xmlxsd_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: xmlxsd_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xmlxsd
      MYSQL_USER: xmlxsd_user
      MYSQL_PASSWORD: xmlxsd_pass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
